import type { NextPage } from 'next'
import Head from 'next/head'
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
export const getServerSideProps = withPageAuthRequired();
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mi Aplicacion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white">
        <div className="relative bg-gray-900">
          <div aria-hidden="true" className="absolute inset-0 overflow-hidden">
            <img
              src="https://tailwindui.com/img/ecommerce-images/home-page-01-hero-full-width.jpg"
              alt=""
              className="w-full h-full object-center object-cover"
            />
          </div>
          <div aria-hidden="true" className="absolute inset-0 bg-gray-900 opacity-50" />
          <div className="relative max-w-3xl mx-auto py-32 px-6 flex flex-col items-center text-center sm:py-64 lg:px-0">
            <h1 className="text-4xl font-extrabold tracking-tight text-white lg:text-6xl">Sistema de Gestión Documentaria</h1>
            <p className="mt-4 text-xl text-white">
              Decreto Supremo N° 029-2021-PCM, Decreto Supremo que aprueba el
              Reglamento del Decreto Legislativo N° 1412, y establece disposiciones
              sobre las condiciones, requisitos y uso de las tecnologías y medios
              electrónicos en el procedimiento administrativo.
            </p>
            <a
              href="#"
              className="mt-8 inline-block bg-white border border-transparent rounded-md py-3 px-8 text-base font-medium text-gray-900 hover:bg-gray-100"
            >
              
            </a>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home
